version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies

  pre_build:
    commands:
      - echo Build started

  build:
    commands:
      - echo Building Docker image
      - docker build -t myapp .

  post_build:
    commands:
      - echo Running container
      - docker run myapp
